services:
  - type: web
    name: quicktable-restaurant
    env: node
    buildCommand: npm install && npm run build && npx drizzle-kit generate && npx drizzle-kit migrate
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quicktable-db
          property: connectionString

databases:
  - name: quicktable-db
    databaseName: quicktable
    user: quicktable_user
    plan: free